integration_tests:
  target: ci
  outputs:
    ci:
      type: spark
      method: session
      schema: integration_tests
      host: localhost
      spark_config:
        spark.jars.packages: io.delta:delta-spark_2.12:3.2.0
        spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
        spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog
